# LOADBEARING: stubs in specialArgs + _module.check=false; scope modules reference inputs.self.packages.* not built for option docs.
{...}: {
  perSystem = {
    pkgs,
    lib,
    ...
  }: let
    stubInputs = {
      self.packages.${pkgs.system} = {
        nixfleet-agent = pkgs.hello;
        nixfleet-control-plane = pkgs.hello;
        nixfleet-cli = pkgs.hello;
      };
    };

    docFor = file: let
      eval = lib.evalModules {
        modules = [
          file
          ({...}: {_module.check = false;})
        ];
        specialArgs = {
          inherit pkgs;
          inputs = stubInputs;
        };
      };
    in
      pkgs.nixosOptionsDoc {inherit (eval) options;};

    sections = [
      {
        heading = "Trust roots - `nixfleet.trust.*`";
        file = ../contracts/trust.nix;
      }
      {
        heading = "Agent - `services.nixfleet-agent.*`";
        file = ./scopes/nixfleet/_agent-options.nix;
      }
      {
        heading = "Control plane - `services.nixfleet-control-plane.*`";
        file = ./scopes/nixfleet/_control-plane.nix;
      }
      {
        heading = "Operator workstation tooling - `nixfleet.operator.*`";
        file = ./scopes/nixfleet/_operator.nix;
      }
      {
        heading = "Binary cache (consumer) - `services.nixfleet-cache.*`";
        file = ./scopes/nixfleet/_cache.nix;
      }
    ];

    sectionMd = {
      heading,
      file,
    }:
      pkgs.runCommand "section.md" {} ''
        printf '## %s\n\n' ${lib.escapeShellArg heading} > $out
        cat ${(docFor file).optionsCommonMark} >> $out
        printf '\n' >> $out
      '';
  in {
    packages.options-doc = pkgs.runCommand "options-doc.md" {} ''
      cat > $out <<'EOF'
      # Module options reference

      Auto-generated by `pkgs.nixosOptionsDoc` from the option
      declarations under `modules/`. Regenerated on every
      `nix run .#docs` build. Edit the `description` strings in the
      module sources to change anything below.

      EOF
      ${lib.concatMapStringsSep "\n" (s: "cat ${sectionMd s} >> $out") sections}
    '';
  };
}
