# vm-fleet-timeout — F3
#
# Covers F3 — Health timeout elapsed → pending machines treated as
# unhealthy → rollout paused via the `timed_out` branch in
# `evaluate_batch` (`control-plane/src/rollout/executor.rs:256–294`).
#
# Topology: cp + web-01. The web-01 node enables `services.nixfleet-agent`
# in Nix config but its systemd unit is neutralised (`wantedBy` forced
# empty) so the agent never starts and therefore never posts a report.
# From the CP's point of view, web-01 is "pre-registered but silent",
# which is exactly the shape that forces `pending_count > 0` to stay
# true until the batch's `started_at + health_timeout` elapses.
#
# The agent is pre-registered on the CP via the admin endpoint
# `POST /api/v1/machines/{id}/register` (with tags=["web"]) so the
# rollout's `tags=["web"]` target resolves to web-01.
#
# Positive assertions:
#   1. The rollout reaches status `paused` within ~health_timeout + a
#      few executor ticks (~2s cadence).
#   2. The events timeline from `GET /api/v1/rollouts/{id}` contains
#      a `batch_failed` event (emitted by executor.rs:331 after the
#      timeout branch pushes `pending_count` into `unhealthy_count`).
#   3. The CP journal contains the "Health timeout elapsed" warn line
#      from executor.rs:273–279.
#
# Negative assertions:
#   1. web-01 never posted ANY report — the `reports` table is empty
#      for machine_id=web-01. This proves the pause reason was
#      "timeout", not "reported failure".
#   2. The nixfleet-agent systemd unit on web-01 is inactive
#      (its masking actually prevented startup).
{
  pkgs,
  lib,
  mkCpNode,
  mkAgentNode,
  mkTlsCerts,
  testPrelude,
  ...
}: let
  testCerts = mkTlsCerts {hostnames = ["web-01"];};

  # Trivial release closure. The agent is never going to fetch it —
  # the whole point of this test is that the machine never reports —
  # but the release registration endpoint still wants a store path.
  web01Closure = pkgs.writeTextDir "share/nixfleet-timeout-web-01" "timeout test web-01";
in
  pkgs.testers.nixosTest {
    name = "vm-fleet-timeout";

    nodes.cp = mkCpNode {inherit testCerts;};

    nodes."web-01" = mkAgentNode {
      inherit testCerts;
      hostName = "web-01";
      tags = ["web"];
      healthInterval = 3;
      extraAgentModules = [
        ({ ...}: {
          environment.systemPackages = [web01Closure];

          # Neutralise the unit: the service file is still generated by
          # `services.nixfleet-agent.enable`, but removing `wantedBy`
          # prevents `multi-user.target` from pulling it in at boot.
          # The result is equivalent to `systemctl mask` for the
          # purposes of this test — the process is never spawned and
          # therefore never reports.
          systemd.services.nixfleet-agent.wantedBy = lib.mkForce [];
        })
      ];
    };

    testScript = let
      web01Path = "${web01Closure}";
    in ''
      import json

      ${testPrelude {}}
      RELEASE_PATH = "${web01Path}"

      # ------------------------------------------------------------------
      # Phase 1 — Start CP, seed admin API key
      # ------------------------------------------------------------------
      cp.start()
      cp.wait_for_unit("nixfleet-control-plane.service")
      cp.wait_for_open_port(8080)

      seed_admin_key(cp)

      # ------------------------------------------------------------------
      # Phase 2 — Start web-01; verify the agent unit is NOT active
      # (wantedBy=[] is equivalent to mask for auto-start purposes).
      # ------------------------------------------------------------------
      web_01.start()
      web_01.wait_for_unit("multi-user.target")

      status = web_01.execute("systemctl is-active nixfleet-agent.service")[1].strip()
      assert status in ("inactive", "failed", "unknown"), \
          f"expected agent unit inactive, got: {status!r}"

      # ------------------------------------------------------------------
      # Phase 3 — Pre-register web-01 on the CP with tag=web so the
      # rollout target resolves to it. The agent will never boot,
      # so this is the ONLY way web-01 enters the fleet.
      # ------------------------------------------------------------------
      register_body = json.dumps({
          "lifecycle": "active",
          "tags": ["web"],
      })
      cp.succeed(
          f"{CURL} {AUTH} -X POST {API}/api/v1/machines/web-01/register "
          f"-H 'Content-Type: application/json' "
          f"-d '{register_body}'"
      )

      cp.wait_until_succeeds(
          f"{CURL} {AUTH} {API}/api/v1/machines "
          f"| python3 -c \"import sys,json; ms=json.load(sys.stdin); "
          f"assert len(ms) == 1, f'expected 1 machine got {{len(ms)}}'; "
          f"assert ms[0]['machine_id'] == 'web-01'\"",
          timeout=30,
      )

      # ------------------------------------------------------------------
      # Phase 4 — Create release + rollout with a short health_timeout
      # and on_failure=pause. health_timeout=5 means the batch must pause
      # within ~5–10s of entering `deploying` (executor ticks at 2s).
      # ------------------------------------------------------------------
      release_body = json.dumps({
          "flake_ref": "vm-fleet-timeout",
          "entries": [
              {
                  "hostname": "web-01",
                  "store_path": RELEASE_PATH,
                  "platform": "x86_64-linux",
                  "tags": ["web"],
              },
          ],
      })
      release = json.loads(cp.succeed(
          f"{CURL} {AUTH} -X POST {API}/api/v1/releases "
          f"-H 'Content-Type: application/json' "
          f"-d '{release_body}'"
      ))
      release_id = release["id"]
      assert release_id.startswith("rel-"), \
          f"expected rel- prefix, got {release_id}"

      rollout_body = json.dumps({
          "release_id": release_id,
          "strategy": "all_at_once",
          "failure_threshold": "0",
          "on_failure": "pause",
          "health_timeout": 5,
          "target": {"tags": ["web"]},
      })
      rollout = json.loads(cp.succeed(
          f"{CURL} {AUTH} -X POST {API}/api/v1/rollouts "
          f"-H 'Content-Type: application/json' "
          f"-d '{rollout_body}'"
      ))
      rollout_id = rollout["rollout_id"]

      # ------------------------------------------------------------------
      # Phase 5 — Positive 1: rollout must reach `paused`
      # ------------------------------------------------------------------
      cp.wait_until_succeeds(
          f"{CURL} {AUTH} {API}/api/v1/rollouts/{rollout_id} "
          f"| python3 -c \"import sys,json; r=json.load(sys.stdin); "
          f"assert r['status'] == 'paused', "
          f"f'expected paused, got {{r[\\\"status\\\"]}}'\"",
          timeout=90,
      )

      # ------------------------------------------------------------------
      # Phase 6 — Positive 2: events timeline contains `batch_failed`.
      # The detail JSON carries batch_index + unhealthy count; since we
      # never reported anything, unhealthy must equal the batch size (1).
      # ------------------------------------------------------------------
      detail = json.loads(cp.succeed(
          f"{CURL} {AUTH} {API}/api/v1/rollouts/{rollout_id}"
      ))
      events = detail.get("events", [])
      batch_failed = [e for e in events if e.get("event_type") == "batch_failed"]
      assert batch_failed, \
          f"expected a batch_failed event, got event types: {[e.get('event_type') for e in events]}"
      bf_detail = batch_failed[0].get("detail", "")
      assert "batch_index" in bf_detail, \
          f"batch_failed event detail missing batch_index: {bf_detail}"
      assert '"unhealthy":1' in bf_detail, \
          f"expected unhealthy=1 in batch_failed detail, got: {bf_detail}"

      # ------------------------------------------------------------------
      # Phase 7 — Positive 3: CP journal contains the `Health timeout
      # elapsed` warn line emitted by executor.rs:273–279.
      # ------------------------------------------------------------------
      cp.succeed(
          "journalctl -u nixfleet-control-plane.service --no-pager "
          "| grep -F 'Health timeout elapsed'"
      )

      # ------------------------------------------------------------------
      # Phase 8 — Negative 1: web-01 never produced any report. The
      # reports table must be empty for machine_id=web-01. This proves
      # the pause reason was "timeout", NOT "reported failure".
      # ------------------------------------------------------------------
      report_count = cp.succeed(
          "sqlite3 /var/lib/nixfleet-cp/state.db "
          "\"SELECT COUNT(*) FROM reports WHERE machine_id = 'web-01'\""
      ).strip()
      assert report_count == "0", \
          f"expected zero reports from web-01, got {report_count}"

      # ------------------------------------------------------------------
      # Phase 9 — Negative 2: re-confirm the agent unit never came up
      # ------------------------------------------------------------------
      status_final = web_01.execute("systemctl is-active nixfleet-agent.service")[1].strip()
      assert status_final in ("inactive", "failed", "unknown"), \
          f"agent unit unexpectedly active at end of test: {status_final!r}"
    '';
  }
