# tests/harness/nodes/cp.nix
#
# Control-plane microVM node for the harness.
#
# Stub behavior: serves a static fleet.resolved.json over HTTPS on :8443
# using mTLS (fleet CA + CP server cert generated by mkTlsCerts). Uses a
# tiny darkhttpd process so we don't depend on crates/control-plane yet.
#
# TODO(5): once the v0.2 control-plane skeleton lands, replace the darkhttpd
# unit below with `services.nixfleet-control-plane` wired to serve the real
# resolved artifact. The mTLS wiring (env and cert paths) stays the same.
{
  lib,
  pkgs,
  testCerts,
  resolvedJsonPath,
  ...
}: {
  # Expose certs + fixture at stable paths on the host VM. Agent microVMs
  # reach this via the qemu user-net gateway (10.0.2.2:8443 from agent
  # POV → host VM's :8443).
  environment.etc = {
    "nixfleet-harness/ca.pem".source = "${testCerts}/ca.pem";
    "nixfleet-harness/cp-cert.pem".source = "${testCerts}/cp-cert.pem";
    "nixfleet-harness/cp-key.pem".source = "${testCerts}/cp-key.pem";
    "nixfleet-harness/fleet.resolved.json".source = resolvedJsonPath;
  };

  networking.firewall.allowedTCPPorts = [8443];

  # TODO(5): replace with services.nixfleet-control-plane once v0.2
  # skeleton exists. For the scaffold we just serve the static fixture
  # over TLS; the reconciler-side verify path is exercised by Stream C
  # unit tests, so the CP here only needs to hand out bytes.
  systemd.services.harness-cp = let
    # `socat` gives us TLS termination + static file response without
    # pulling in a full webserver. It's in nixpkgs and starts in <100ms.
    responder = pkgs.writeShellScript "harness-cp-responder" ''
      set -eu
      body=$(cat /etc/nixfleet-harness/fleet.resolved.json)
      len=$(printf '%s' "$body" | wc -c)
      printf 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s' "$len" "$body"
    '';
    socatOpts = lib.concatStringsSep "," [
      "OPENSSL-LISTEN:8443"
      "reuseaddr"
      "fork"
      "cert=/etc/nixfleet-harness/cp-cert.pem"
      "key=/etc/nixfleet-harness/cp-key.pem"
      "cafile=/etc/nixfleet-harness/ca.pem"
      "verify=1"
    ];
    launcher = pkgs.writeShellScript "harness-cp-launcher" ''
      exec ${pkgs.socat}/bin/socat -v "${socatOpts}" "EXEC:${responder}"
    '';
  in {
    description = "Nixfleet harness CP stub (serves fleet.resolved.json)";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${launcher}";
      Restart = "on-failure";
      RestartSec = 2;
    };
  };

  system.stateVersion = lib.mkDefault "24.11";
}
