# VM tests for infrastructure scopes (firewall, monitoring, backup, secrets).
# Tests firewall hardening, node exporter, backup timer, and secrets host key generation.
{inputs, ...}: {
  perSystem = {
    pkgs,
    system,
    lib,
    ...
  }: let
    helpers = import ./_lib/helpers.nix {inherit lib;};

    mkTestNode = helpers.mkTestNode {
      inherit inputs;
      hostSpecModule = ../_shared/host-spec-module.nix;
    };

    defaultTestSpec = helpers.defaultTestSpec;
  in
    lib.optionalAttrs (system == "x86_64-linux") {
      checks = {
        # --- vm-firewall: SSH rate limiting and drop logging ---
        vm-firewall = pkgs.testers.nixosTest {
          name = "vm-firewall";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # nftables should be active
            machine.succeed("nft list ruleset | grep -q 'chain input'")

            # SSH rate limiting rules should be present
            machine.succeed("nft list ruleset | grep -q 'limit rate 5/minute'")

            # Drop logging should be enabled
            machine.succeed("nft list ruleset | grep -qi 'log'")
          '';
        };

        # --- vm-monitoring: node exporter responds on port ---
        vm-monitoring = pkgs.testers.nixosTest {
          name = "vm-monitoring";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              {
                nixfleet.monitoring.nodeExporter = {
                  enable = true;
                  openFirewall = true;
                };
              }
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")
            machine.wait_for_unit("prometheus-node-exporter.service")
            machine.wait_for_open_port(9100)

            # Verify metrics endpoint responds with Prometheus text format
            output = machine.succeed("curl -sf http://localhost:9100/metrics")
            assert "# HELP" in output, f"Expected Prometheus metrics, got: {output[:200]}"

            # Verify systemd collector is active (we enabled it)
            assert "node_systemd" in output, "Expected node_systemd metrics from systemd collector"
          '';
        };

        # --- vm-backup: timer registered and service skeleton exists ---
        vm-backup = pkgs.testers.nixosTest {
          name = "vm-backup";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              ({pkgs, ...}: {
                nixfleet.backup = {
                  enable = true;
                  schedule = "*-*-* *:*:00";
                };
                # Provide a dummy ExecStart so the service can run
                systemd.services.nixfleet-backup.serviceConfig.ExecStart = "${pkgs.coreutils}/bin/true";
              })
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # Timer should be registered
            machine.succeed("systemctl list-timers | grep -q 'nixfleet-backup'")

            # Manually trigger the backup service
            machine.succeed("systemctl start nixfleet-backup.service")

            # Status file should be written after successful run
            machine.succeed("test -f /var/lib/nixfleet-backup/status.json")
            output = machine.succeed("cat /var/lib/nixfleet-backup/status.json")
            assert '"status": "success"' in output, f"Expected success status, got: {output}"
          '';
        };

        # --- vm-secrets: host key generation on first boot ---
        vm-secrets = pkgs.testers.nixosTest {
          name = "vm-secrets";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              {
                nixfleet.secrets.enable = true;
              }
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # Host key should exist (either pre-existing or generated by nixfleet-host-key-check)
            machine.succeed("test -f /etc/ssh/ssh_host_ed25519_key")
            machine.succeed("test -f /etc/ssh/ssh_host_ed25519_key.pub")

            # Key should have correct permissions
            machine.succeed("stat -c '%a' /etc/ssh/ssh_host_ed25519_key | grep -q '600'")
          '';
        };

        # --- vm-attic-server: Attic binary cache server starts and responds ---
        vm-attic-server = let
          # Generate a signing key at build time for the test
          signingKeyFile = pkgs.runCommand "attic-test-signing-key" {} ''
            ${pkgs.nix}/bin/nix-store --generate-binary-cache-key test-cache "$out" /dev/null
          '';
        in
          pkgs.testers.nixosTest {
            name = "vm-attic-server";

            nodes.server = mkTestNode {
              hostSpecValues = defaultTestSpec // {hostName = "server";};
              extraModules = [
                {
                  services.nixfleet-attic-server = {
                    enable = true;
                    signingKeyFile = "${signingKeyFile}";
                  };
                }
              ];
            };

            nodes.client = mkTestNode {
              hostSpecValues = defaultTestSpec // {hostName = "client";};
            };

            testScript = ''
              server.start()
              client.start()

              server.wait_for_unit("multi-user.target")
              server.wait_for_unit("nixfleet-attic-server.service")
              server.wait_for_open_port(8081)

              # Attic server should respond on port 8081
              server.succeed("curl -sf http://localhost:8081/")

              # Storage directory should be created by StateDirectory=
              server.succeed("test -d /var/lib/nixfleet-attic")
            '';
          };

        # --- vm-attic-client: Attic client configures Nix substituters and installs CLI ---
        vm-attic-client = pkgs.testers.nixosTest {
          name = "vm-attic-client";

          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              {
                services.nixfleet-attic-client = {
                  enable = true;
                  cacheUrl = "http://cache.example.com";
                  publicKey = "test-cache:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
                };
              }
            ];
          };

          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # Nix substituters should include the cache URL
            machine.succeed("nix show-config | grep substituters | grep cache.example.com")

            # Nix trusted-public-keys should include the signing key
            machine.succeed("nix show-config | grep trusted-public-keys | grep test-cache")

            # attic CLI should be available
            machine.succeed("which attic")
          '';
        };

        # --- vm-backup-restic: restic backend wires up correctly ---
        vm-backup-restic = let
          passwordFile = pkgs.writeText "restic-test-password" "test-password";
          repositoryPath = "/tmp/restic-test-repo";
        in
          pkgs.testers.nixosTest {
            name = "vm-backup-restic";

            nodes.machine = mkTestNode {
              hostSpecValues = defaultTestSpec;
              extraModules = [
                {
                  nixfleet.backup = {
                    enable = true;
                    backend = "restic";
                    schedule = "*-*-* *:*:00";
                    paths = ["/tmp"];
                    restic = {
                      repository = repositoryPath;
                      passwordFile = "${passwordFile}";
                    };
                  };
                }
              ];
            };

            testScript = ''
              machine.wait_for_unit("multi-user.target")

              # Backup timer should be registered
              machine.succeed("systemctl list-timers | grep nixfleet-backup")

              # restic binary should be available (installed by backend = "restic")
              machine.succeed("which restic")

              # Backup service ExecStart should reference restic
              machine.succeed("systemctl cat nixfleet-backup.service | grep restic")
            '';
          };
      };
    };
}
