# VM tests for infrastructure scopes (firewall, monitoring, backup, secrets).
# Tests firewall hardening, node exporter, backup timer, and secrets host key generation.
{inputs, ...}: {
  perSystem = {
    pkgs,
    system,
    lib,
    ...
  }: let
    helpers = import ./_lib/helpers.nix {inherit lib;};

    mkTestNode = helpers.mkTestNode {
      inherit inputs;
      hostSpecModule = ../_shared/host-spec-module.nix;
    };

    defaultTestSpec = helpers.defaultTestSpec;
  in
    lib.optionalAttrs (system == "x86_64-linux") {
      checks = {
        # --- vm-firewall: SSH rate limiting and drop logging ---
        vm-firewall = pkgs.testers.nixosTest {
          name = "vm-firewall";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # nftables should be active
            machine.succeed("nft list ruleset | grep -q 'chain input'")

            # SSH rate limiting rules should be present
            machine.succeed("nft list ruleset | grep -q 'limit rate 5/minute'")

            # Drop logging should be enabled
            machine.succeed("nft list ruleset | grep -qi 'log'")
          '';
        };

        # --- vm-monitoring: node exporter responds on port ---
        vm-monitoring = pkgs.testers.nixosTest {
          name = "vm-monitoring";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              {
                nixfleet.monitoring.nodeExporter = {
                  enable = true;
                  openFirewall = true;
                };
              }
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")
            machine.wait_for_unit("prometheus-node-exporter.service")
            machine.wait_for_open_port(9100)

            # Verify metrics endpoint responds with Prometheus text format
            output = machine.succeed("curl -sf http://localhost:9100/metrics")
            assert "# HELP" in output, f"Expected Prometheus metrics, got: {output[:200]}"

            # Verify systemd collector is active (we enabled it)
            assert "node_systemd" in output, "Expected node_systemd metrics from systemd collector"
          '';
        };

        # --- vm-backup: timer registered and service skeleton exists ---
        vm-backup = pkgs.testers.nixosTest {
          name = "vm-backup";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              ({pkgs, ...}: {
                nixfleet.backup = {
                  enable = true;
                  schedule = "*-*-* *:*:00";
                };
                # Provide a dummy ExecStart so the service can run
                systemd.services.nixfleet-backup.serviceConfig.ExecStart = "${pkgs.coreutils}/bin/true";
              })
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # Timer should be registered
            machine.succeed("systemctl list-timers | grep -q 'nixfleet-backup'")

            # Manually trigger the backup service
            machine.succeed("systemctl start nixfleet-backup.service")

            # Status file should be written after successful run
            machine.succeed("test -f /var/lib/nixfleet-backup/status.json")
            output = machine.succeed("cat /var/lib/nixfleet-backup/status.json")
            assert '"status": "success"' in output, f"Expected success status, got: {output}"
          '';
        };

        # --- vm-secrets: host key generation on first boot ---
        vm-secrets = pkgs.testers.nixosTest {
          name = "vm-secrets";
          nodes.machine = mkTestNode {
            hostSpecValues = defaultTestSpec;
            extraModules = [
              {
                nixfleet.secrets.enable = true;
              }
            ];
          };
          testScript = ''
            machine.wait_for_unit("multi-user.target")

            # Host key should exist (either pre-existing or generated by nixfleet-host-key-check)
            machine.succeed("test -f /etc/ssh/ssh_host_ed25519_key")
            machine.succeed("test -f /etc/ssh/ssh_host_ed25519_key.pub")

            # Key should have correct permissions
            machine.succeed("stat -c '%a' /etc/ssh/ssh_host_ed25519_key | grep -q '600'")
          '';
        };
      };
    };
}
