# Core Darwin module - framework mechanism only.
#
# Opinions stripped:
# - `system.defaults.*` (trackpad / finder / dock behavior) - those are
#   opinions; fleet repos set them under their own scopes.
# - Dock management still exposes `options.local.dock` here because the
#   *mechanism* (dockutil-driven declarative dock) is framework-level;
#   fleet repos populate `local.dock.entries` under their own scopes.
# - User creation for the primary user moves to
#   `arcanesys/nixfleet-scopes` roles.
#
# What stays here:
# - nix settings (substituters, trusted keys, experimental features)
# - TouchID PAM (universally applicable convenience)
# - dock option declaration + activation script (mechanism)
# - `system.primaryUser` pass-through from hostSpec (Darwin-specific
#   identity wiring that nix-darwin requires)
# - `system.stateVersion` baseline (override per host)
{
  config,
  pkgs,
  lib,
  ...
}: let
  hS = config.hostSpec;
  dockCfg = config.local.dock;
  inherit (pkgs) dockutil;
in {
  # --- dock option module (mechanism - fleet populates entries) ---
  options.local.dock = {
    enable = lib.mkOption {
      type = lib.types.bool;
      description = "Whether to manage the macOS Dock from Nix.";
      default = true;
      example = false;
    };
    entries = lib.mkOption {
      description = ''
        Entries to place on the Dock. Fleet repos populate this list
        with the apps, folders, and URLs they want managed.
      '';
      type = lib.types.listOf (lib.types.submodule {
        options = {
          path = lib.mkOption {
            type = lib.types.str;
            description = "Filesystem path or URL of the dock entry.";
            example = "/Applications/Safari.app";
          };
          section = lib.mkOption {
            type = lib.types.enum ["apps" "others"];
            default = "apps";
            description = "Dock section this entry belongs to.";
          };
          options = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Extra options forwarded to dockutil.";
          };
        };
      });
      default = [];
      example = lib.literalExpression ''
        [
          { path = "/Applications/Safari.app"; }
          { path = "/Applications/Terminal.app"; }
        ]
      '';
    };
  };

  config = lib.mkMerge [
    {
      # --- nixpkgs ---
      nixpkgs.config = {
        allowUnfree = true;
        allowBroken = false;
        allowInsecure = false;
        allowUnsupportedSystem = true;
      };

      # --- nix (Determinate Nix compatible) ---
      #
      # Determinate Nix owns /etc/nix/nix.conf (regenerated by determinate-nixd).
      # nix.enable = false prevents nix-darwin from fighting over it.
      # Custom settings go in /etc/nix/nix.custom.conf, which Determinate's
      # nix.conf includes via `!include nix.custom.conf`.
      #
      # We use `extra-*` prefixes so our values APPEND to Determinate's
      # defaults (e.g. trusted-users = root is preserved) rather than
      # replacing them.
      #
      # Written via postActivation (not environment.etc) because /etc/nix/
      # is owned by Determinate Nix - nix-darwin's etc activation refuses
      # to overwrite existing non-symlink files there.
      # Other modules (e.g. remote-builders scope) append with cat >>.
      nix = {
        package = pkgs.nix;
        enable = false;
      };

      system.activationScripts.postActivation.text = lib.mkBefore ''
        cat > /etc/nix/nix.custom.conf <<'NIX_CUSTOM'
        extra-trusted-users = @admin ${hS.userName}
        extra-substituters = https://nix-community.cachix.org https://cache.nixos.org
        extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
        auto-optimise-store = true
        NIX_CUSTOM
      '';

      # --- sudo (TouchID) ---
      security.pam.services.sudo_local.touchIdAuth = true;
      environment.etc."pam.d/sudo_local".text = ''
        # Managed by Nix Darwin
        auth       optional       ${pkgs.pam-reattach}/lib/pam/pam_reattach.so ignore_ssh
        auth       sufficient     pam_tid.so
      '';

      # --- identity pass-through ---
      # hS.userName derives from nixfleet.operators._primaryName when the
      # operators Darwin scope (nixfleet-scopes.scopes.operatorsDarwin or
      # nixfleet-scopes.darwinModules.operators) is active. Without it,
      # consumers must set hostSpec.userName explicitly (as darwin-agent-test
      # does in fleet.nix). Auto-importing the operators Darwin scope here
      # is a consumer responsibility - Darwin fleets add it via their mkHost
      # modules list, unlike NixOS where the impermanence scope is
      # auto-imported by mkHost for service-module option compatibility.
      system.stateVersion = lib.mkDefault 4;
      system.checks.verifyNixPath = false;
      system.primaryUser = "${hS.userName}";

      hostSpec.isDarwin = true;
    }

    # --- dock management (mechanism only; entries come from fleet) ---
    (lib.mkIf dockCfg.enable {
      system.activationScripts.postActivation.text = let
        normalize = path:
          if lib.hasSuffix ".app" path
          then path + "/"
          else path;
        entryURI = path:
          "file://"
          + (
            builtins.replaceStrings
            [" " "!" "\"" "#" "$" "%" "&" "'" "(" ")"]
            ["%20" "%21" "%22" "%23" "%24" "%25" "%26" "%27" "%28" "%29"]
            (normalize path)
          );
        wantURIs = lib.concatMapStrings (entry: "${entryURI entry.path}\n") dockCfg.entries;
        createEntries =
          lib.concatMapStrings (
            entry: "sudo -u ${hS.userName} ${dockutil}/bin/dockutil --no-restart --add '${entry.path}' --section ${entry.section} ${entry.options}\n"
          )
          dockCfg.entries;
      in ''
        echo >&2 "Setting up the Dock..."
        haveURIs="$(sudo -u ${hS.userName} ${dockutil}/bin/dockutil --list | ${pkgs.coreutils}/bin/cut -f2)"
        if ! diff -wu <(echo -n "$haveURIs") <(echo -n '${wantURIs}') >&2 ; then
          echo >&2 "Resetting Dock."
          sudo -u ${hS.userName} ${dockutil}/bin/dockutil --no-restart --remove all
          ${createEntries}
          sudo -u ${hS.userName} killall Dock
        else
          echo >&2 "Dock setup complete."
        fi
      '';
    })
  ];
}
